python-application/app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
import logging
from logging.config import dictConfig

from app.helpers.memoize import memoizer


def _base_app(app_config):
    """
    initialise a barebone flask app.
    :arg config_name [string] - the name of the environment; must be a key in the "config" dict
    """
    configure_logging(app_config)

    app = Flask(__name__)
    app.config.from_object(app_config)
    app_config.init_app(app)
    app.static_folder='templates/static'
    app.static_url_path='/static'
    Bootstrap(app)

    return app


def create_app(app_config):
    """
    The factory function that creates the Flask app.
    Register all blueprints here
    """

    import logging as log
    log.info(f"Creating an app for environment: {app_config.__class__.__name__}")

    app = _base_app(app_config)
    memoizer.init_app(app)

    from .api import api as api_blueprint
    app.register_blueprint(api_blueprint, url_prefix="/api")

    from .pages import pages as main_blueprint
    app.register_blueprint(main_blueprint)

    return app


def configure_logging(app_config):
    """
    http://flask.pocoo.org/docs/1.0/logging/
    "If possible, configure logging before creating the application object.
    """
    dictConfig({
        'version': 1,
        'formatters': {'default': {
            'format': '[%(asctime)s] %(levelname)s in %(module)s: %(message)s',
        }},
        'handlers': {'wsgi': {
            'class': 'logging.StreamHandler',
            'stream': 'ext://flask.logging.wsgi_errors_stream',
            'formatter': 'default'
        }},
        'root': {
            'level': app_config.LOG_LEVEL,
            'handlers': ['wsgi']
        }
    })
    logging.getLogger('botocore').setLevel(logging.CRITICAL)

python-application/app/api/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

from . import views

python-application/app/api/views.py
from . import api
from app.helpers.api_utils import make_json_response


@api.route('/api_ping')
def ping():
    return make_json_response({"result": "pong"})

python-application/app/pages/__init__.py
from flask import Blueprint

pages = Blueprint('pages', __name__)

from . import views

python-application/app/pages/views.py
from flask import render_template, current_app, request, redirect, flash
from . import pages
from boto3 import client

sns = client('sns')


def send_sms(phone, msg):

    sns.publish(
        # 'TopicArn='arn:aws:sns:us-east-1:750385577863:test',
        PhoneNumber=phone,
        Message=msg
    )


@pages.route('/', methods=['GET', 'POST'])
def index_stores():
    if request.method == 'POST':
        print(request.data)
        phone, msg = request.form.get('phonenumber'), request.form.get('msg')
        print(phone, msg)
        flash(f'Successfully sent a text message to <strong>{phone}</strong>')
        send_sms(phone, msg)
        return redirect('/')

    return render_template('index.html.jinja')

python-application/app/templates/index.html.jinja
{% extends "bootstrap/base.html" %}
{% block title %}Stores{% endblock %}

{% block content %}
<style>
/* CSS used here will be applied after bootstrap.css */

body {
 background: url('/static/bg.jpg') no-repeat center center fixed;
 -webkit-background-size: cover;
 -moz-background-size: cover;
 -o-background-size: cover;
 background-size: cover;
}

.panel-default {
 opacity: 0.9;
 margin-top:30px;
}
.form-group.last {
 margin-bottom:0px;
}
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                  <strong>Send a message</strong>
                </div>
                <div class="panel-body">
                    {% with messages = get_flashed_messages() %}
                          {% if messages %}
                      <div class="panel-text">
                            <div class="alert alert-success" role="alert">
                            {% for message in messages %}
                               {{ message }}
                            {% endfor %}
                            </div>
                            </div>
                          {% endif %}
                        {% endwith %}

                    <form class="form-horizontal" role="form" action="{{url_for('pages.index_stores')}}" method="POST">
                    <div class="form-group">
                        <label for="phonenumber" class="col-sm-3 control-label">
                            Phone</label>
                        <div class="col-sm-9">
                            <input type="phone" class="form-control" name="phonenumber" id="phonenumber" placeholder="+35988123456" required="True">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="msg" class="col-sm-3 control-label">
                            Message</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="msg" name="msg" placeholder="Type your message" required="True">
                        </div>
                    </div>

                    <div class="form-group last">
                        <div class="col-sm-offset-3 col-sm-9">
                            <button type="submit" value="submit" class="btn btn-success btn-sm">
                                Send</button>

                        </div>
                    </div>
                    </form>
                </div>
                <div class="panel-footer">
                    progressbg.net devops course 2019</a></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}